# Generated by Django 4.2.23 on 2025-07-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='category',
            field=models.CharField(choices=[('Casual', 'Casual'), ('Sick', 'Sick'), ('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
