# Generated by Django 4.2.23 on 2025-07-28 12:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emp_app', '0004_remove_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryBreakup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic', models.FloatField()),
                ('hra', models.FloatField()),
                ('income_tax', models.FloatField()),
                ('deductions', models.FloatField()),
                ('gross_salary', models.FloatField()),
                ('net_salary', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_credited', models.DateField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.employee')),
                ('salary_breakup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.salarybreakup')),
            ],
        ),
    ]
