# Generated by Django 4.2.23 on 2025-07-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.CharField(default='Mumbai', max_length=300),
        ),
    ]
