# Generated by Django 4.2.23 on 2025-07-28 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0003_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
